name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libvtk9-dev

      - name: Run installDeps.sh
        run: bash installDeps.sh

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF

      - name: Build
        run: cmake --build build --config Release -j2

      - name: Test Release
        working-directory: build
        run: ctest
      
      - name: Configure CMake Coverage
        run: cmake -B build-coverage -S . -DCMAKE_BUILD_TYPE=Release -DENABLE_CUDA=OFF -DENABLE_COVERAGE=ON

      - name: Build Coverage
        run: cmake --build build-coverage

      - name: Test Debug Coverage
        working-directory: build-coverage 
        run: ctest --output-on-failure

      - name: Coverage
        working-directory: build-coverage 
        run: lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
      
      - name: Publish Coverage
        working-directory: build-coverage 
        run: lcov --remove coverage.info     '/usr/*'     '*/tests/*'     '*/googletest/*'     '*/cli11/*'     '*/build/_deps/*' --output-file coverage.info --ignore-errors mismatch    --output-file coverage_filtered.info




